// ================================================================
// MAGIC HOME — FILE CHỈNH SỬA NỘI DUNG DỊCH VỤ
// ================================================================
// Files in /public are served as static assets — reference them as
// URL strings (never import them). Use import.meta.env.BASE_URL so
// paths work correctly regardless of the Vite `base` config.
// ================================================================

// ── LOGO ─────────────────────────────────────────────────────────
export const logoImg = `/logo/logo.png`;

// ── HERO SLIDESHOW ───────────────────────────────────────────────
export const heroImages: string[] = [
  `/Photos/cover.jpg`,
  `/DaytoDusk/cover.jpg`,
  `/Retouch/cover.jpg`,
  `/VirtualHomeStaging/cover.jpg`,
  `/Floorplan/cover.jpg`,
  `/cover_video/covervideo.jpg`,
];

// ── STEP BY STEP IMAGES ──────────────────────────────────────────
// Thêm ảnh vào thư mục /public/StepByStep/ và khai báo đường dẫn ở đây
export const stepByStepImages: string[] = [
  `/StepByStep/StepByStep.jpg`,
];

// ── PORTFOLIO IMAGES ─────────────────────────────────────────────
// Thêm ảnh vào thư mục /public/Portfolio/ và khai báo đường dẫn ở đây
export const portfolioImages: string[] = [
  `/Portfolio/Portfolio1.jpg`,
  `/Portfolio/Portfolio2.jpg`,
  `/Portfolio/Portfolio3.jpg`,
  `/Portfolio/Portfolio4.jpg`,
  `/Portfolio/Portfolio5.jpg`,
  `/Portfolio/Portfolio6.jpg`,
  `/Portfolio/Portfolio7.jpg`,
  `/Portfolio/Portfolio8.jpg`,
  `/Portfolio/Portfolio9.jpg`,
  `/Portfolio/Portfolio10.jpg`,
  `/Portfolio/Portfolio11.jpg`,
  `/Portfolio/Portfolio12.jpg`,
  `/Portfolio/Portfolio13.jpg`,
  `/Portfolio/Portfolio14.jpg`,
  `/Portfolio/Portfolio15.jpg`,
  `/Portfolio/Portfolio16.jpg`,
  `/Portfolio/Portfolio17.jpg`,
  `/Portfolio/Portfolio18.jpg`,
  `/Portfolio/Portfolio19.jpg`,
  `/Portfolio/Portfolio20.jpg`,
  `/Portfolio/Portfolio21.jpg`,
  `/Portfolio/Portfolio22.jpg`,
  `/Portfolio/Portfolio23.jpg`,
  `/Portfolio/Portfolio24.jpg`,
  `/Portfolio/Portfolio25.jpg`,
  `/Portfolio/Portfolio26.jpg`,
  `/Portfolio/Portfolio27.jpg`,
  `/Portfolio/Portfolio28.jpg`,
  `/Portfolio/Portfolio29.jpg`,
  `/Portfolio/Portfolio30.jpg`,
  `/Portfolio/Portfolio31.jpg`,
  `/Portfolio/Portfolio32.jpg`,
  `/Portfolio/Portfolio33.jpg`,
  `/Portfolio/Portfolio34.jpg`,
  `/Portfolio/Portfolio35.jpg`,
  `/Portfolio/Portfolio36.jpg`,
  `/Portfolio/Portfolio37.jpg`,
  `/Portfolio/Portfolio38.jpg`,
  `/Portfolio/Portfolio39.jpg`,
  `/Portfolio/Portfolio40.jpg`,
  `/Portfolio/Portfolio41.jpg`,
  `/Portfolio/Portfolio42.jpg`,
  `/Portfolio/Portfolio43.jpg`,
  `/Portfolio/Portfolio44.jpg`,
  `/Portfolio/Portfolio45.jpg`,
  `/Portfolio/Portfolio46.jpg`,
  `/Portfolio/Portfolio47.jpg`,
  `/Portfolio/Portfolio48.jpg`,
  `/Portfolio/Portfolio49.jpg`,
  `/Portfolio/Portfolio50.jpg`,
  `/Portfolio/Portfolio51.jpg`,
  `/Portfolio/Portfolio52.jpg`,
  `/Portfolio/Portfolio53.jpg`,
  `/Portfolio/Portfolio54.jpg`,
  `/Portfolio/Portfolio55.jpg`,
  `/Portfolio/Portfolio56.jpg`,
  `/Portfolio/Portfolio57.jpg`,
  `/Portfolio/Portfolio58.jpg`,
  `/Portfolio/Portfolio59.jpg`,
  `/Portfolio/Portfolio60.jpg`,
  `/Portfolio/Portfolio61.jpg`,
  `/Portfolio/Portfolio62.jpg`,
  `/Portfolio/Portfolio63.jpg`,
  `/Portfolio/Portfolio64.jpg`,
  `/Portfolio/Portfolio65.jpg`,
  `/Portfolio/Portfolio66.jpg`,
  `/Portfolio/Portfolio67.jpg`,
  `/Portfolio/Portfolio68.jpg`,
  `/Portfolio/Portfolio69.jpg`,
  `/Portfolio/Portfolio70.jpg`,
  `/Portfolio/Portfolio71.jpg`,
  `/Portfolio/Portfolio72.jpg`,
  `/Portfolio/Portfolio73.jpg`,
  `/Portfolio/Portfolio74.jpg`,
  `/Portfolio/Portfolio75.jpg`,
  `/Portfolio/Portfolio76.jpg`,
  `/Portfolio/Portfolio77.jpg`,
  `/Portfolio/Portfolio78.jpg`,
  `/Portfolio/Portfolio79.jpg`,
  `/Portfolio/Portfolio80.jpg`,
  `/Portfolio/Portfolio81.jpg`,
  `/Portfolio/Portfolio82.jpg`,
  `/Portfolio/Portfolio83.jpg`,
  `/Portfolio/Portfolio84.jpg`,
  `/Portfolio/Portfolio85.jpg`,
  `/Portfolio/Portfolio86.jpg`,
  `/Portfolio/Portfolio87.jpg`,
  `/Portfolio/Portfolio88.jpg`,
  `/Portfolio/Portfolio89.jpg`,
  `/Portfolio/Portfolio90.jpg`,
  `/Portfolio/Portfolio91.jpg`,
  `/Portfolio/Portfolio92.jpg`,
  `/Portfolio/Portfolio93.jpg`,
  `/Portfolio/Portfolio94.jpg`,
  `/Portfolio/Portfolio95.jpg`,
  `/Portfolio/Portfolio96.jpg`,
  `/Portfolio/Portfolio97.jpg`,
  `/Portfolio/Portfolio98.jpg`,
  `/Portfolio/Portfolio99.jpg`,
  `/Portfolio/Portfolio100.jpg`,
  `/Portfolio/Portfolio101.jpg`,
  `/Portfolio/Portfolio102.jpg`,
  `/Portfolio/Portfolio103.jpg`,
  `/Portfolio/Portfolio104.jpg`,
];

// ================================================================
// DANH SÁCH DỊCH VỤ
// ================================================================
export const services = [

  // ── 1. PHOTOS ─────────────────────────────────────────────────
  {
    id: 'photos',
    name: 'Photos',
    subtitle: 'HDR – Single Exposure – Flambient',
    price: 'From $0.5',
    priceUnit: 'per image',
    deliveryTime: '<12 hours delivery',
    description: 'Professional real estate photo editing — color correction, sky replacement, HDR blending and exposure enhancement to make every property shine.',
    coverImage: `/Photos/cover.jpg`,
    images: [
      { id: '1', url: `/Photos/photos1.jpg`, caption: '' },
      { id: '2', url: `/Photos/photos2.jpg`, caption: '' },
      { id: '3', url: `/Photos/photos3.jpg`, caption: '' },
      { id: '4', url: `/Photos/photos4.jpg`, caption: '' },
      { id: '5', url: `/Photos/photos5.jpg`, caption: '' },
      { id: '6', url: `/Photos/photos6.jpg`, caption: '' },
      { id: '7', url: `/Photos/photos7.jpg`, caption: '' },
      { id: '8', url: `/Photos/photos8.jpg`, caption: '' },
      { id: '9', url: `/Photos/photos9.jpg`, caption: '' },
      { id: '10', url: `/Photos/photos10.jpg`, caption: '' },
      { id: '11', url: `/Photos/photos11.jpg`, caption: '' },
      { id: '12', url: `/Photos/photos12.jpg`, caption: '' },
      { id: '13', url: `/Photos/photos13.jpg`, caption: '' },
      { id: '14', url: `/Photos/photos14.jpg`, caption: '' },
      { id: '15', url: `/Photos/photos15.jpg`, caption: '' },
      { id: '16', url: `/Photos/photos16.jpg`, caption: '' },
      { id: '17', url: `/Photos/photos17.jpg`, caption: '' },
      { id: '18', url: `/Photos/photos18.jpg`, caption: '' },
      { id: '19', url: `/Photos/photos19.jpg`, caption: '' },
      { id: '20', url: `/Photos/photos20.jpg`, caption: '' },
      { id: '21', url: `/Photos/photos21.jpg`, caption: '' },
      { id: '22', url: `/Photos/photos22.jpg`, caption: '' },
      { id: '23', url: `/Photos/photos23.jpg`, caption: '' },
      { id: '24', url: `/Photos/photos24.jpg`, caption: '' },
      { id: '25', url: `/Photos/photos25.jpg`, caption: '' },
      { id: '26', url: `/Photos/photos26.jpg`, caption: '' },
      { id: '27', url: `/Photos/photos27.jpg`, caption: '' },
      { id: '28', url: `/Photos/photos28.jpg`, caption: '' },
      { id: '29', url: `/Photos/photos29.jpg`, caption: '' },
      { id: '30', url: `/Photos/photos30.jpg`, caption: '' },
      { id: '31', url: `/Photos/photos31.jpg`, caption: '' },
      { id: '32', url: `/Photos/photos32.jpg`, caption: '' },
      { id: '33', url: `/Photos/photos33.jpg`, caption: '' },
      { id: '34', url: `/Photos/photos34.jpg`, caption: '' },
      { id: '35', url: `/Photos/photos35.jpg`, caption: '' },
      { id: '36', url: `/Photos/photos36.jpg`, caption: '' },
      { id: '37', url: `/Photos/photos37.jpg`, caption: '' },
      { id: '38', url: `/Photos/photos38.jpg`, caption: '' },
      { id: '39', url: `/Photos/photos39.jpg`, caption: '' },
      { id: '40', url: `/Photos/photos40.jpg`, caption: '' },
      { id: '41', url: `/Photos/photos41.jpg`, caption: '' },
      { id: '42', url: `/Photos/photos42.jpg`, caption: '' },
      { id: '43', url: `/Photos/photos43.jpg`, caption: '' },
      { id: '44', url: `/Photos/photos44.jpg`, caption: '' },
      { id: '45', url: `/Photos/photos45.jpg`, caption: '' },
      { id: '46', url: `/Photos/photos46.jpg`, caption: '' },
      { id: '47', url: `/Photos/photos47.jpg`, caption: '' },
      { id: '48', url: `/Photos/photos48.jpg`, caption: '' },
      { id: '49', url: `/Photos/photos49.jpg`, caption: '' },
      { id: '50', url: `/Photos/photos50.jpg`, caption: '' },
      { id: '51', url: `/Photos/photos51.jpg`, caption: '' },
      { id: '52', url: `/Photos/photos52.jpg`, caption: '' },
      { id: '53', url: `/Photos/photos53.jpg`, caption: '' },
      { id: '54', url: `/Photos/photos54.jpg`, caption: '' },
      { id: '55', url: `/Photos/photos55.jpg`, caption: '' },
      { id: '56', url: `/Photos/photos56.jpg`, caption: '' },
      { id: '57', url: `/Photos/photos57.jpg`, caption: '' },
      { id: '58', url: `/Photos/photos58.jpg`, caption: '' },
      { id: '59', url: `/Photos/photos59.jpg`, caption: '' },
      { id: '60', url: `/Photos/photos60.jpg`, caption: '' },
      { id: '61', url: `/Photos/photos61.jpg`, caption: '' },
      { id: '62', url: `/Photos/photos62.jpg`, caption: '' },
      { id: '63', url: `/Photos/photos63.jpg`, caption: '' },
      { id: '64', url: `/Photos/photos64.jpg`, caption: '' },
      { id: '65', url: `/Photos/photos65.jpg`, caption: '' },
      { id: '66', url: `/Photos/photos66.jpg`, caption: '' },
      { id: '67', url: `/Photos/photos67.jpg`, caption: '' },
      { id: '68', url: `/Photos/photos68.jpg`, caption: '' },
      { id: '69', url: `/Photos/photos69.jpg`, caption: '' },
      { id: '70', url: `/Photos/photos70.jpg`, caption: '' },
      { id: '71', url: `/Photos/photos71.jpg`, caption: '' },
    ],
    videos: [],
    beforeAfterPairs: [
      { id: 'ba1', before: `/BeforeAfterSlider/Photos/before1.jpg`,  after: `/BeforeAfterSlider/Photos/affter1.jpg`,  label: 'Before & After 1' },
      { id: 'ba2', before: `/BeforeAfterSlider/Photos/before2.jpg`, after: `/BeforeAfterSlider/Photos/affter2.jpg`, label: 'Before & After 2' },
    ],
  },

  // ── 2. DAY TO DUSK ────────────────────────────────────────────
  {
    id: 'day-to-dusk',
    name: 'Day To Dusk',
    subtitle: 'Twilight – Sunset Sky – Glow Effect',
    price: 'From $5',
    priceUnit: 'per image',
    deliveryTime: '<12 hours delivery',
    description: 'Turn flat daytime exteriors into dramatic twilight shots — glowing windows, vivid sunset skies and ambient lighting that captivates buyers.',
    coverImage: `/DaytoDusk/cover.jpg`,
    images: [
      { id: '1', url: `/DaytoDusk/DaytoDusk1.jpg`, caption: '' },
      { id: '2', url: `/DaytoDusk/DaytoDusk2.jpg`, caption: '' },
      { id: '3', url: `/DaytoDusk/DaytoDusk3.jpg`, caption: '' },
      { id: '4', url: `/DaytoDusk/DaytoDusk4.jpg`, caption: '' },
      { id: '5', url: `/DaytoDusk/DaytoDusk5.jpg`, caption: '' },
      { id: '6', url: `/DaytoDusk/DaytoDusk6.jpg`, caption: '' },
      { id: '7', url: `/DaytoDusk/DaytoDusk7.jpg`, caption: '' },
      { id: '8', url: `/DaytoDusk/DaytoDusk8.jpg`, caption: '' },
      { id: '9', url: `/DaytoDusk/DaytoDusk9.jpg`, caption: '' },
      { id: '10', url: `/DaytoDusk/DaytoDusk10.jpg`, caption: '' },
      { id: '11', url: `/DaytoDusk/DaytoDusk11.jpg`, caption: '' },
      { id: '12', url: `/DaytoDusk/DaytoDusk12.jpg`, caption: '' },
      { id: '13', url: `/DaytoDusk/DaytoDusk13.jpg`, caption: '' },
      { id: '14', url: `/DaytoDusk/DaytoDusk14.jpg`, caption: '' },
      { id: '15', url: `/DaytoDusk/DaytoDusk15.jpg`, caption: '' },
      { id: '16', url: `/DaytoDusk/DaytoDusk16.jpg`, caption: '' },
      { id: '17', url: `/DaytoDusk/DaytoDusk17.jpg`, caption: '' },
      { id: '18', url: `/DaytoDusk/DaytoDusk18.jpg`, caption: '' },
      { id: '19', url: `/DaytoDusk/DaytoDusk19.jpg`, caption: '' },
    ],
    videos: [],
    beforeAfterPairs: [
      { id: 'ba1', before: `/BeforeAfterSlider/DayToDusk/before1.jpg`, after: `/BeforeAfterSlider/DayToDusk/affter1.jpg`, label: 'Before & After 1' },
      { id: 'ba2', before: `/BeforeAfterSlider/DayToDusk/before2.jpg`, after: `/BeforeAfterSlider/DayToDusk/affter2.jpg`, label: 'Before & After 2' },
    ],
  },

  // ── 3. RETOUCH ────────────────────────────────────────────────
  {
    id: 'retouch',
    name: 'Retouch',
    subtitle: 'Object Removal – Sky Enhancement – Cleanup',
    price: 'From $1',
    priceUnit: 'per image',
    deliveryTime: '<12 hours delivery',
    description: 'Remove distractions, fix imperfections and polish every detail. Object removal, sky enhancement and full-scene cleanup for flawless listings.',
    coverImage: `/Retouch/cover.jpg`,
    images: [
      { id: '1', url: `/Retouch/Retouch1.jpg`, caption: '' },
      { id: '2', url: `/Retouch/Retouch2.jpg`, caption: '' },
      { id: '3', url: `/Retouch/Retouch3.jpg`, caption: '' },
      { id: '4', url: `/Retouch/Retouch4.jpg`, caption: '' },
      { id: '5', url: `/Retouch/Retouch5.jpg`, caption: '' },
      { id: '6', url: `/Retouch/Retouch6.jpg`, caption: '' },
      { id: '7', url: `/Retouch/Retouch7.jpg`, caption: '' },
      { id: '8', url: `/Retouch/Retouch8.jpg`, caption: '' },
      { id: '9', url: `/Retouch/Retouch9.jpg`, caption: '' },
      { id: '10', url: `/Retouch/Retouch10.jpg`, caption: '' },
      { id: '11', url: `/Retouch/Retouch11.jpg`, caption: '' },
      { id: '12', url: `/Retouch/Retouch12.jpg`, caption: '' },
      { id: '13', url: `/Retouch/Retouch13.jpg`, caption: '' },
      { id: '14', url: `/Retouch/Retouch14.jpg`, caption: '' },
      { id: '15', url: `/Retouch/Retouch15.jpg`, caption: '' },
    ],
    videos: [],
    beforeAfterPairs: [
      { id: 'ba1', before: `/BeforeAfterSlider/Retouch/before1.jpg`, after: `/BeforeAfterSlider/Retouch/affter1.jpg`, label: 'Before & After 1' },
      { id: 'ba2', before: `/BeforeAfterSlider/Retouch/before2.jpg`, after: `/BeforeAfterSlider/Retouch/affter2.jpg`, label: 'Before & After 2' },
    ],
  },

  // ── 4. GRASS REPLACEMENT ────────────────────────────────────────────────
  {
    id: 'grass-replacement',
    name: 'Grass Replacement',
    subtitle: 'Turf Repair – Patch Filling – Greener Lawns',
    price: 'From $1',
    priceUnit: 'per image',
    deliveryTime: '<12 hours delivery',
    description: 'Replace worn or patchy lawns with natural-looking grass replacement and patch repairs to boost curb appeal in listing photos.',
    coverImage: `/GrassReplacement/cover.jpg`,
    images: [
      { id: '1', url: `/GrassReplacement/GrassReplacement1.jpg`, caption: '' },
      { id: '2', url: `/GrassReplacement/GrassReplacement2.jpg`, caption: '' },
      { id: '3', url: `/GrassReplacement/GrassReplacement3.jpg`, caption: '' },
      { id: '4', url: `/GrassReplacement/GrassReplacement4.jpg`, caption: '' },
      { id: '5', url: `/GrassReplacement/GrassReplacement5.jpg`, caption: '' },
      { id: '6', url: `/GrassReplacement/GrassReplacement6.jpg`, caption: '' },
    ],
    videos: [],
    beforeAfterPairs: [
      { id: 'ba1', before: `/BeforeAfterSlider/GrassReplacement/before1.jpg`, after: `/BeforeAfterSlider/GrassReplacement/affter1.jpg`, label: 'Before & After 1' },
      { id: 'ba2', before: `/BeforeAfterSlider/GrassReplacement/before2.jpg`, after: `/BeforeAfterSlider/GrassReplacement/affter2.jpg`, label: 'Before & After 2' },
    ],
  },

  // ── 5. VIRTUAL HOME STAGING ───────────────────────────────────
  {
    id: 'virtual-staging',
    name: 'Virtual Home Staging',
    subtitle: 'High Quality – Furniture Placement – Renovation',
    price: 'From $15',
    priceUnit: 'per image',
    deliveryTime: '<12 hours delivery',
    description: 'Digitally furnish empty rooms with photorealistic furniture and décor. Help buyers visualise the full lifestyle potential of any property.',
    coverImage: `/VirtualHomeStaging/cover.jpg`,
    images: [
      { id: '1', url: `/VirtualHomeStaging/VirtualHomeStaging1.jpg`, caption: '' },
      { id: '2', url: `/VirtualHomeStaging/VirtualHomeStaging2.jpg`, caption: '' },
      { id: '3', url: `/VirtualHomeStaging/VirtualHomeStaging3.jpg`, caption: '' },
      { id: '4', url: `/VirtualHomeStaging/VirtualHomeStaging4.jpg`, caption: '' },
      { id: '5', url: `/VirtualHomeStaging/VirtualHomeStaging5.jpg`, caption: '' },
      { id: '6', url: `/VirtualHomeStaging/VirtualHomeStaging6.jpg`, caption: '' },
      { id: '7', url: `/VirtualHomeStaging/VirtualHomeStaging7.jpg`, caption: '' },
      { id: '8', url: `/VirtualHomeStaging/VirtualHomeStaging8.jpg`, caption: '' },
      { id: '9', url: `/VirtualHomeStaging/VirtualHomeStaging9.jpg`, caption: '' },
      { id: '10', url: `/VirtualHomeStaging/VirtualHomeStaging10.jpg`, caption: '' },
      { id: '11', url: `/VirtualHomeStaging/VirtualHomeStaging11.jpg`, caption: '' },
      { id: '11', url: `/VirtualHomeStaging/VirtualHomeStaging12.jpg`, caption: '' },
      { id: '11', url: `/VirtualHomeStaging/VirtualHomeStaging13.jpg`, caption: '' },
      { id: '11', url: `/VirtualHomeStaging/VirtualHomeStaging14.jpg`, caption: '' },
    ],
    videos: [],
    beforeAfterPairs: [
      { id: 'ba1', before: `/BeforeAfterSlider/VirtualHomeStaging/before1.jpg`, after: `/BeforeAfterSlider/VirtualHomeStaging/affter1.jpg`, label: 'Before & After 1' },
      { id: 'ba2', before: `/BeforeAfterSlider/VirtualHomeStaging/before2.jpg`, after: `/BeforeAfterSlider/VirtualHomeStaging/affter2.jpg`, label: 'Before & After 2' },
    ],
  },

  // ── 6. VIDEO ──────────────────────────────────────────────────
  {
    id: 'video',
    name: 'Video',
    subtitle: 'Cinematic – Drone Footage – Branded Films',
    price: 'From $20',
    priceUnit: 'per video',
    deliveryTime: '<12 hours delivery',
    description: 'Cinematic real estate video production and post-production. Smooth walkthroughs, drone footage editing and branded property films.',
    coverImage: `/cover_video/covervideo.jpg`,
    images: [],
    videos: [
      { id: '1', youtubeUrl: 'https://www.youtube.com/watch?v=Ic1yI9tK5tY', title: '' },
      { id: '2', youtubeUrl: 'https://youtube.com/shorts/-rsEcD7w2NQ?feature=share', title: '' },
      { id: '3', youtubeUrl: 'https://youtube.com/shorts/HuhoB-9i4lM?feature=share', title: '' },
      { id: '4', youtubeUrl: 'https://youtu.be/SQeRYv9Aa-4', title: '' },
      { id: '5', youtubeUrl: 'https://youtu.be/qtTNSrZUwUg', title: '' },
      { id: '6', youtubeUrl: 'https://youtu.be/wzPvYNWmtFc', title: '' },
      { id: '7', youtubeUrl: 'https://youtube.com/shorts/jajXRVGUqZA?feature=share', title: '' },

    ],
  },

  // ── 7. FLOORPLAN ──────────────────────────────────────────────
  {
    id: 'floorplan',
    name: 'Floorplan',
    subtitle: '2D & 3D – Precise Layout – Professional',
    price: 'From $10',
    priceUnit: 'per plan',
    deliveryTime: '<12 hours delivery',
    description: 'Precise 2D and 3D floor plans drawn from photos or rough sketches. Clean, professional layouts that help buyers understand every space.',
    coverImage: `/Floorplan/cover.jpg`,
    images: [
      { id: '1', url: `/Floorplan/Floorplan1.jpg`, caption: '' },
      { id: '2', url: `/Floorplan/Floorplan2.jpg`, caption: '' },
      { id: '3', url: `/Floorplan/Floorplan3.jpg`, caption: '' },
      { id: '4', url: `/Floorplan/Floorplan4.jpg`, caption: '' },
      { id: '5', url: `/Floorplan/Floorplan5.jpg`, caption: '' },
      { id: '6', url: `/Floorplan/Floorplan6.jpg`, caption: '' },
      { id: '7', url: `/Floorplan/Floorplan7.jpg`, caption: '' },
      { id: '8', url: `/Floorplan/Floorplan8.jpg`, caption: '' },
      { id: '9', url: `/Floorplan/Floorplan9.jpg`, caption: '' },
      { id: '10', url: `/Floorplan/Floorplan10.jpg`, caption: '' },
    ],
    videos: [],
  },

];
